### ISSUE TITLE
执行sqlmlutils.SQLPackageManager报错

### ISSUE THREAD

**Issue by dqaudithillstone** [MicrosoftDocs/sql-docs.zh-cn#134]
[执行sqlmlutils.SQLPackageManager(connection).install("c:/temp/text-tools/text_tools-1.0.0-py3-none-any.whl")时报错]
错误信息如下：
A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
An external script error occurred:

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:\PROGRA~1\SQLSER~1\MSSQL1~1.MSS\MSSQL\EXTENS~1\MSSQLSERVER01\1F3DE0EB-6B03-4779-912D-C35147428D27\sqlindb.py", line 58, in transform
    return_val = func(*pos_args, **args)
  File "C:\PROGRA~1\SQLSER~1\MSSQL1~1.MSS\MSSQL\EXTENS~1\MSSQLSERVER01\1F3DE0EB-6B03-4779-912D-C35147428D27\sqlindb.py", line 36, in get_server_info
    "impl_version_info": pep425tags.get_impl_version_info(),
AttributeError: module 'pip._internal.pep425tags' has no attribute 'get_impl_version_info'

SqlSatelliteCall error: Error in execution.  Check the output for more information.
STDOUT message(s) from external script:
SqlSatelliteCall function failed. Please see the console output for more information.
Traceback (most recent call last):
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 406, in rx_sql_satellite_call
    rx_native_call("SqlSatelliteCall", params)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 291, in rx_native_call
    ret = px_call(functionname, params)
RuntimeError: revoscalepy function failed.
Traceback (most recent call last):
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\sqlqueryexecutor.py", line 55, in execute
    self._mssqlconn.execute_query(builder.base_script, builder.params)
  File "src\_mssql.pyx", line 1064, in _mssql.MSSQLConnection.execute_query
  File "src\_mssql.pyx", line 1096, in _mssql.MSSQLConnection.execute_query
  File "src\_mssql.pyx", line 1294, in _mssql.MSSQLConnection.get_result
  File "src\_mssql.pyx", line 1641, in _mssql.check_cancel_and_raise
  File "src\_mssql.pyx", line 1683, in _mssql.maybe_raise_MSSQLDatabaseException
_mssql.MSSQLDatabaseException: (39004, b"A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 72, in install
    self._install_from_file(package, scope, upgrade, out_file=out_file)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 165, in _install_from_file
    pipdownloader = PipDownloader(self._connection_info, temporary_directory, target_package_file)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\packagemanagement\pipdownloader.py", line 15, in __init__
    server_info = SQLPythonExecutor(connection).execute_function_in_sql(servermethods.get_server_info)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\sqlpythonexecutor.py", line 47, in execute_function_in_sql
    rows = execute_query(SpeesBuilderFromFunction(func, input_data_query, *args, **kwargs), self._connection_info)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\sqlqueryexecutor.py", line 19, in execute_query
    return executor.execute(builder, out_file=out_file)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\sqlqueryexecutor.py", line 61, in execute
    raise RuntimeError("Error in SQL Execution") from e
RuntimeError: Error in SQL Execution

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bb790fba-2d19-b1a7-3935-6ec5f9207fcc
* Version Independent ID: f350cf6b-0fa8-6d76-8433-f3f752e62ecf
* Content: [使用 pip 安装 Python 包 - SQL Server Machine Learning Services](https://docs.microsoft.com/zh-cn/sql/advanced-analytics/package-management/install-additional-python-packages-on-sql-server?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/package-management/install-additional-python-packages-on-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/advanced-analytics/package-management/install-additional-python-packages-on-sql-server.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by srvbpigh** [comment]
Hello, @dqaudithillstone
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好，@dqaudithillstone， 

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。 

如果你有任何与文档相关的反馈，请通过此渠道进行记录。 

我们非常感谢你对我们的文章的贡献。 

Microsoft DOCS 国际团队

**Comment by dqaudithillstone** [comment]
File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 72, in install
    self._install_from_file(package, scope, upgrade, out_file=out_file)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 165, in _install_from_file
    pipdownloader = PipDownloader(self._connection_info, temporary_directory, target_package_file)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\packagemanagement\pipdownloader.py", line 15, in __init__
    server_info = SQLPythonExecutor(connection).execute_function_in_sql(servermethods.get_server_info)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\sqlpythonexecutor.py", line 47, in execute_function_in_sql
    rows = execute_query(SpeesBuilderFromFunction(func, input_data_query, *args, **kwargs), self._connection_info)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\sqlqueryexecutor.py", line 19, in execute_query
    return executor.execute(builder, out_file=out_file)
  File "C:\Program Files\sqlserver2017\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\sqlmlutils\sqlqueryexecutor.py", line 61, in execute
    raise RuntimeError("Error in SQL Execution") from e
RuntimeError: Error in SQL Execution
